#!/usr/bin/env python3
"""genkeywords.py - keep the keyword lists of the tutorial highlighter in step with the spec.

Usage:
    python script/genkeywords.py            rewrite the generated block of tutorial/js/eve1.js
    python script/genkeywords.py --check    only report whether the block is up to date (exit 1 if not)

The source is spec/lexical/keywords.json (D-094, D-116). The block between the lines
"BEGIN GENERATED" and "END GENERATED" of eve1.js is replaced; the rest of the file is not touched.
Categories become the CSS classes of content-code.css:
    statement, region, declaration (reserved)  -> keyword, anywhere in a line
    operator                                   -> operator
    block (reserved)                           -> control
    block (contextual: all, one, other)        -> constant, anywhere in a line
    declaration (contextual: public...)        -> keyword, only when the word opens a line
OVERRIDES moves single words to another class. Words that are not in keywords.json (types, the
library functions print, write and read, the legacy database words) stay in eve1.js, outside the block.

`python script/speccheck.py` calls --check, so a stale block is reported with the other problems.
Python 3, standard library only; the file keeps its line endings.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KEYWORDS = ROOT / "spec" / "lexical" / "keywords.json"
TARGET = ROOT / "tutorial" / "js" / "eve1.js"
BEGIN = "// BEGIN GENERATED by script/genkeywords.py from spec/lexical/keywords.json: do not edit by hand"
END = "// END GENERATED"
OVERRIDES = {"is": "operator"}      # `is` also ends a declaration header; it reads best as an operator


def classify():
    groups = {"keyword": [], "operator": [], "control": [], "constant": [], "opening": []}
    for item in json.loads(KEYWORDS.read_text(encoding="utf-8"))["items"]:
        word, cat, ctx = item["id"], item["category"], item.get("contextual", False)
        if word in OVERRIDES:
            groups[OVERRIDES[word]].append(word)
        elif cat == "operator":
            groups["operator"].append(word)
        elif cat == "block":
            groups["constant" if ctx else "control"].append(word)
        elif ctx:
            groups["opening"].append(word)
        else:
            groups["keyword"].append(word)
    return {k: sorted(v) for k, v in groups.items()}


def wrap(words, width=100, indent=8):
    lines, line = [], ""
    for w in words:
        if line and len(line) + 1 + len(w) > width - indent:
            lines.append(line)
            line = w
        else:
            line = (line + " " + w) if line else w
    lines.append(line)
    return ("\n" + " " * indent).join(lines)


def block(groups):
    pad = " " * 4
    out = [pad + BEGIN]
    for cls in ("keyword", "operator", "control", "constant"):
        out.append(f'{pad}define("{cls}", `')
        out.append(" " * 8 + wrap(groups[cls]) + "`);")
    out.append(f"{pad}// contextual declaration words are highlighted only when they open a line")
    out.append(f"{pad}const DECLARATIONS = new Set(`")
    out.append(" " * 8 + wrap(groups["opening"]) + '`.trim().split(/\\s+/));')
    out.append(pad + END)
    return "\n".join(out).split("\n")     # one list item per line


def main_check():
    return main(check=True)


def main(check=None):
    if check is None:
        check = "--check" in sys.argv
    raw = TARGET.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    lines = raw.split(nl)
    try:
        a = next(i for i, l in enumerate(lines) if BEGIN in l)
        b = next(i for i, l in enumerate(lines) if END in l and i > a)
    except StopIteration:
        print("genkeywords: markers not found in", TARGET)
        return 1
    new = lines[:a] + block(classify()) + lines[b + 1:]
    if new == lines:
        print("genkeywords: eve1.js is up to date")
        return 0
    if check:
        print("genkeywords: eve1.js is stale; run python script/genkeywords.py")
        return 1
    TARGET.write_bytes(nl.join(new).encode("utf-8"))
    print("genkeywords: eve1.js updated (tutorial repo: commit it with git -C tutorial)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
